% Compar what happens when use a different number of total solutions, keeping 
% 20 solutions for iterating 

datasets = {'brcaMatchedTN','ERpn','kirckirp','luadlusc','lumAB'};
rand_nsols = [20 100 1000 5000];
dw_nsols = [20 50 100 1000];
fnames = {'meansolsBacc','meansolsAUC','meansolsLogloss'};
figure;
for n = 1 : length(datasets)
    d = datasets{n};
    load(['~/Dropbox-Work/Wuxi/Results/bootstrap_resamples/' d '_bootstrap_resamples/results.mat'],'*pc*testperf*');
    rand_testperf = [rand_pc65_nsols_20_testperf; rand_pc65_nsols_50_testperf; rand_pc65_nsols_100_testperf; ...
        rand_pc65_nsols_1000_testperf];
    sa_testperf = [SA_nr_1000_nswps_1000_pc65_at_5_nsols_20_testperf_simple; ...
        SA_nr_1000_nswps_1000_pc65_at_5_nsols_50_testperf_simple; ...
        SA_nr_1000_nswps_1000_pc65_at_5_nsols_100_testperf_simple; ...
        SA_nr_1000_nswps_1000_pc65_at_5_nsols_1000_testperf_simple];
%     cinit0d5_dw_testperf = [cinit0d5_pc65_at_5_nsols_20_testperf_simple; ...
%         cinit0d5_pc65_at_5_nsols_50_testperf_simple; ...
%         cinit0d5_pc65_at_5_nsols_100_testperf_simple; ...
%         cinit0d5_pc65_at_5_nsols_1000_testperf_simple];
%     cinit1_dw_testperf = [cinit1_pc65_at_5_nsols_20_testperf_simple;...
%         cinit1_pc65_at_5_nsols_50_testperf_simple;...
%         cinit1_pc65_at_5_nsols_100_testperf_simple; ...
%         cinit1_pc65_at_5_nsols_1000_testperf_simple];
%     cinit3_dw_testperf = [cinit3_pc65_at_5_nsols_20_testperf_simple;...
%         cinit3_pc65_at_5_nsols_50_testperf_simple; ...
%         cinit3_pc65_at_5_nsols_100_testperf_simple; ...
%         cinit3_pc65_at_5_nsols_1000_testperf_simple];
    cinit8_dw_testperf = [cinit8_pc65_at_5_nsols_20_testperf_simple; ...
        cinit8_pc65_at_5_nsols_50_testperf_simple; ...
        cinit8_pc65_at_5_nsols_100_testperf_simple; ...
        cinit8_pc65_at_5_nsols_1000_testperf_simple];
    for m = 1 : 3
        subplot(3,5,n+(m-1)*5); hold on;
        rand_metric = reshape([rand_testperf.(fnames{m})],4,100);
        sa_metric = reshape([sa_testperf.(fnames{m})],4,100);
%         cinit0d5_dw_metric = reshape([cinit0d5_dw_testperf.(fnames{m})],4,100);
%         cinit1_dw_metric = reshape([cinit1_dw_testperf.(fnames{m})],4,100);
%         cinit3_dw_metric = reshape([cinit3_dw_testperf.(fnames{m})],4,100);
        cinit8_dw_metric = reshape([cinit8_dw_testperf.(fnames{m})],4,100);
%         errorbar(dw_nsols,mean(cinit0d5_dw_metric,2),std(cinit0d5_dw_metric,[],2),'o');
%         errorbar(dw_nsols,mean(cinit1_dw_metric,2),std(cinit1_dw_metric,[],2),'o');
%         errorbar(dw_nsols,mean(cinit3_dw_metric,2),std(cinit3_dw_metric,[],2),'o');
        errorbar(dw_nsols,mean(cinit8_dw_metric,2),std(cinit8_dw_metric,[],2),'o-');
        errorbar(dw_nsols,mean(sa_metric,2),std(sa_metric,[],2),'o-');
        errorbar(dw_nsols,mean(rand_metric,2),std(rand_metric,[],2),'o-');
        set(gca,'xscale','log');
    end
    clearvars *testperf*
end
legend('DWs','SA','Rand');
